### ISSUE TITLE
Unexpected error fetching ********** data: 'X-CSRF-Token'

### ISSUE THREAD

**Issue by hiddevanbrussel** [rootnegativ1/unifi-wifi#12]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.unifi_wifi.coordinator
Source: helpers/update_coordinator.py:300
Integration: Unifi Wifi (documentation, issues)
First occurred: 14:45:42 (1 occurrences)
Last logged: 14:45:42

Unexpected error fetching ********** data: 'X-CSRF-Token'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/coordinator.py", line 111, in _async_update_data
    return await self._update_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_wifi/coordinator.py", line 247, in _update_info
    csrf_token = resp.headers[UNIFI_CSRF_TOKEN]
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'X-CSRF-Token'

**Comment by rootnegativ1** [comment]
Interesting, I got the same error this morning. I've noticed some weird API behavior recently. I'm running a UDM on 3.2.7 firmware with Network Application version 8.0.24. What hardware/versions are you using?

**Comment by rootnegativ1** [comment]
see https://github.com/rootnegativ1/unifi-wifi/pull/13
